//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int trans_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public string book_name { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
